# 이 워크 플로우의 이름 GitHub Actions 탭에서 노출될 이름
name: CI

# 트리거 설정 언제 이 워크플로우를 실행할지
on:
  # Main 브랜치에 push 될때
  push:
    branches: [main]

  # main으로 향하는 PR이 열리거나 업데이트 할때 이건 알아두는게 좋다고 함.
  pull_request:
    branches: [main]

# 실행할 작업들
jobs:
  # 지금은 test라는 이름 job 하나만 만들었다. 이름은 임의로 지어도 되기는 한다. test는 관례적인 이름
  test:
    # 이 job을 어떤 환경(가상 머신)에서 실행할지, GitHub이 매 개념과 비슷한 원리다.
    runs-on: ubuntu-latest
    timeout-minutes: 10

    # GitHub Actions 에서 DB를 띄우는 방법
    # services: 로컬에서는 docker compose up -d 로 Postgres를 미리 띄워두고 테스트를 했지만.
    # CI 환경(매번 새로 생기는 가정 머신)에서는 그 컨테이너가 없으니 워크 플로우 안에서 직접 띄어줘야 한다.
    services: # job 실행 중에 같이 띄울 부가 서버스(컨테이너)들. 여기 정의하면 job 스탭들이 자동으로 켜진다.
      postgres: # 서비스이름 임의로 지어도 되지만 관례상 이미지 이름과 맞춘다.
        image: postgres:15 # 로컬 환경에서 썼던 image 버전과 맞춘다.
        env: # 컨테이너 환경변수. docker-compose.yaml 에 environment 와 같은 개념
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres_test
        ports:
          - 5432:5432
        # 헬스체크 설정. Postgres가 완전히 켜져서 연결 받을 준비가 됐는지 주기적으로 확인해줘야 한다.
        # 컨테이너가 시작됐다 는 것과 연결 받을 준비가 됐다 는건 다른 타이밍이라, 아래 체크 없이 바로 테스트를 돌리면 실패할수 있다.
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      # Redis
      redis:
        image: redis
        ports:
          - 6379:6379

    # 순서대로 실행할 명령러들.
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: Node.js 설치
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 의존성 설치
        run: yarn install --frozen-lockfile

      - name: 유닛 테스트
        # 테스트 코드를 실행.
        run: yarn test

      # E2E 테스트 실행하는 step
      - name: E2E 테스트 실행
        run: yarn test:e2e
        # 환경변수 직접 주입 .env.test 파일을 그대로 쓰는게 아니라, 워크폴로우 파일 안에서 직접 값을 넘겨줄 수 있다.
        # dotenv/ConfigModule은 토봉 이미 설정된 환경변수가 있으면 그걸 우선으로 하고 파링은 보조 수단으로 동작한다.
        env:
          NODE_ENV: test
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USERNAME: postgres
          DB_PASSWORD: postgres
          DB_NAME: postgres_test
          # ${{}} JWT 시크릿 키 값은 워크폴루우 파일에 저장 되면 안된다.
          JWT_ACCESS_SECRET: ${{ secrets.JWT_ACCESS_SECRET }}
          JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
          HASH_ROUND: 10
          REDIS_HOST: localhost
          REDIS_PORT: 6379

  # 어제 배운 내용을 토대로 위에 CI 가 실행 된 이후 아래 CD 가 실행 된다. 자동화
  deploy:
    needs: test # test job이 성공해야만 이 job이 시작된다. 이게 없으면 test 와 deploy 가 동시에 실행 되려 고 한다.
    runs-on: ubuntu-latest

    # **PR을 열 떄도 이 워크폴로우가 도는데, PR 단계 에서는 절대 배포되면 안된다.**
    # 진짜 main에 병합/push된 경우에만 배포 하도록 막는거다.
    if: github.ref == 'refs/heads/main'

    steps:
      - name: SSH 키 등록
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

        # ssh-keyscan으로 미리 이 서버는 신뢰할 수 있다 고 등록해두는거다.
        # Are you sure you want to continue connecting (yes/no)? 라고 뜬다면 처음 접속할때 확인하는 보안 절차
      - name: 서버 known_hosts 등록
        run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: 서버에 배포
        # | yaml 에서 여러 줄 문자열을 그대로 유지 할때 쓰는 문법. | 다음 줄 부터 들여쓰기 된 내용 전체가 하나의 명령어 불록이 된다.
        # ssh ${{계정@호스트}} << 'EOF' 이건 Here Document 라는 셀 문법이다. << 'EOF' 부터 EOF 까지 사이의 모든 줄을,
        # SSH 로 접급한 원격 서버에서 순서대로 실행 해라 는 뜻이다.
        # 'EOF' 따옴표를 준 이유 따옴표가 없으면 ${{}} 같은 변수가 로컬 GitHub Actions에서 먼저 해석될수도 있다.
        # 따옴표를 붙이면 "이 안의 내용은 그대로" 해석 하지 말고 서버로 그대로 보내라 라는 뜻이다.
        run: |
          ssh ${{ secrets.EC2_USERNAME }}${{ secrets.Ec2_HOST }} << 'EOF'
            cd -/nestjs-reservation-api-project
            git pull origin main
            npm install
            npm run build
            pm2 restart nestjs-app
          EOF
